# Generated by Django 2.2.5 on 2019-10-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsblog', '0002_auto_20191003_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Shreyas Tulsi', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
